
version: "3.8"
services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ProductCatalogDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: deadnote
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"     